-- =========================================================
-- Scheduler application tables
-- PostgreSQL
-- =========================================================


-- =========================================================
-- 1. Job execution log
-- =========================================================

CREATE TABLE sched_exec_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fire_instance_id VARCHAR(120) NOT NULL,
    job_name VARCHAR(190) NOT NULL,
    job_group VARCHAR(190) NOT NULL,
    trigger_name VARCHAR(190),
    trigger_group VARCHAR(190),
    scheduled_fire_time TIMESTAMP(6),
    actual_fire_time TIMESTAMP(6),
    finished_at TIMESTAMP(6),
    run_millis BIGINT,
    status VARCHAR(20) NOT NULL,
    exception_message VARCHAR(2000),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sched_exec_log
IS '스케줄러 Job 실행 이력';

COMMENT ON COLUMN sched_exec_log.log_id
IS '실행 로그 식별자';

COMMENT ON COLUMN sched_exec_log.fire_instance_id
IS 'Quartz 실행 인스턴스 식별자';

COMMENT ON COLUMN sched_exec_log.job_name
IS 'Job 이름';

COMMENT ON COLUMN sched_exec_log.job_group
IS 'Job 그룹';

COMMENT ON COLUMN sched_exec_log.trigger_name
IS 'Trigger 이름';

COMMENT ON COLUMN sched_exec_log.trigger_group
IS 'Trigger 그룹';

COMMENT ON COLUMN sched_exec_log.scheduled_fire_time
IS '예정 실행 일시';

COMMENT ON COLUMN sched_exec_log.actual_fire_time
IS '실제 실행 시작 일시';

COMMENT ON COLUMN sched_exec_log.finished_at
IS '실행 종료 일시';

COMMENT ON COLUMN sched_exec_log.run_millis
IS '실행 소요 시간(ms)';

COMMENT ON COLUMN sched_exec_log.status
IS '실행 상태';

COMMENT ON COLUMN sched_exec_log.exception_message
IS '예외 메시지';

COMMENT ON COLUMN sched_exec_log.created_at
IS '로그 생성 일시';


-- =========================================================
-- 2. External API
-- =========================================================

CREATE TABLE sched_external_api (
    external_api_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name VARCHAR(100) NOT NULL,
    api_url VARCHAR(1000) NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    enabled CHAR(1) NOT NULL DEFAULT 'Y',

    retry_enabled CHAR(1) NOT NULL DEFAULT 'N',
    max_retry_count INTEGER NOT NULL DEFAULT 0,
    retry_interval_sec INTEGER NOT NULL DEFAULT 0,

    description VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_sched_external_api_enabled
        CHECK (enabled IN ('Y', 'N')),

    CONSTRAINT ck_sched_external_api_method
        CHECK (http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE')),

    CONSTRAINT ck_sched_external_api_retry_enabled
        CHECK (retry_enabled IN ('Y', 'N')),

    CONSTRAINT ck_sched_external_api_max_retry_count
        CHECK (max_retry_count >= 0),

    CONSTRAINT ck_sched_external_api_retry_interval_sec
        CHECK (retry_interval_sec >= 0)
);

COMMENT ON TABLE sched_external_api
IS '외부 API 기본 정보';

COMMENT ON COLUMN sched_external_api.external_api_id
IS '외부 API 식별자';

COMMENT ON COLUMN sched_external_api.api_name
IS '외부 API 이름';

COMMENT ON COLUMN sched_external_api.api_url
IS '외부 API 호출 URL';

COMMENT ON COLUMN sched_external_api.http_method
IS 'HTTP 메서드(GET, POST, PUT, PATCH, DELETE)';

COMMENT ON COLUMN sched_external_api.enabled
IS '사용 여부(Y/N)';

COMMENT ON COLUMN sched_external_api.retry_enabled
IS 'External API 호출 실패 시 재시도 사용 여부(Y/N)';

COMMENT ON COLUMN sched_external_api.max_retry_count
IS '최초 호출 실패 후 추가 재시도 최대 횟수';

COMMENT ON COLUMN sched_external_api.retry_interval_sec
IS 'External API 재시도 간격(초)';

COMMENT ON COLUMN sched_external_api.description
IS '외부 API 설명';

COMMENT ON COLUMN sched_external_api.created_at
IS '생성 일시';

COMMENT ON COLUMN sched_external_api.updated_at
IS '수정 일시';


-- =========================================================
-- 3. External API parameter
-- =========================================================

CREATE TABLE sched_external_api_param (
    param_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_api_id BIGINT NOT NULL,
    param_location VARCHAR(20) NOT NULL,
    param_name VARCHAR(100) NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    param_value VARCHAR(2000),
    value_format VARCHAR(100),
    required_yn CHAR(1) NOT NULL DEFAULT 'N',
    sort_order INTEGER NOT NULL DEFAULT 0,
    description VARCHAR(500),

    CONSTRAINT fk_external_api_param_api
        FOREIGN KEY (external_api_id)
        REFERENCES sched_external_api (external_api_id),

    CONSTRAINT ck_external_api_param_location
        CHECK (param_location IN ('HEADER', 'QUERY', 'BODY')),

    CONSTRAINT ck_external_api_param_required
        CHECK (required_yn IN ('Y', 'N')),

    CONSTRAINT ck_external_api_param_value_type
        CHECK (
            value_type IN (
                'STATIC',
                'CURRENT_DATE',
                'CURRENT_TIME',
                'CURRENT_DATETIME'
            )
        )
);

COMMENT ON TABLE sched_external_api_param
IS 'External API 호출 파라미터 정보';

COMMENT ON COLUMN sched_external_api_param.param_id
IS 'External API 파라미터 식별자';

COMMENT ON COLUMN sched_external_api_param.external_api_id
IS 'External API 식별자';

COMMENT ON COLUMN sched_external_api_param.param_location
IS '파라미터 위치(HEADER, QUERY, BODY)';

COMMENT ON COLUMN sched_external_api_param.param_name
IS '파라미터 이름';

COMMENT ON COLUMN sched_external_api_param.value_type
IS '파라미터 값 유형(STATIC, CURRENT_DATE, CURRENT_TIME, CURRENT_DATETIME)';

COMMENT ON COLUMN sched_external_api_param.param_value
IS '파라미터 값';

COMMENT ON COLUMN sched_external_api_param.value_format
IS '동적 값 생성 시 사용할 포맷';

COMMENT ON COLUMN sched_external_api_param.required_yn
IS '필수 파라미터 여부(Y/N)';

COMMENT ON COLUMN sched_external_api_param.sort_order
IS '파라미터 표시 및 처리 순서';

COMMENT ON COLUMN sched_external_api_param.description
IS '파라미터 설명';


-- =========================================================
-- 4. External API call log
-- =========================================================

CREATE TABLE sched_external_api_call_log (
    api_call_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_api_id BIGINT NOT NULL,
    fire_instance_id VARCHAR(200),
    execution_id VARCHAR(36),
    attempt_no INTEGER NOT NULL DEFAULT 1,
    http_status INTEGER,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP(6),
    run_millis BIGINT,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(2000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE sched_external_api_call_log
IS 'External API 호출 이력';

COMMENT ON COLUMN sched_external_api_call_log.api_call_log_id
IS 'External API 호출 로그 식별자';

COMMENT ON COLUMN sched_external_api_call_log.external_api_id
IS 'External API 식별자';

COMMENT ON COLUMN sched_external_api_call_log.fire_instance_id
IS 'Quartz 실행 인스턴스 식별자';

COMMENT ON COLUMN sched_external_api_call_log.execution_id
IS 'External API 1회 실행 단위를 식별하는 ID';

COMMENT ON COLUMN sched_external_api_call_log.attempt_no
IS 'External API 호출 시도 번호(1: 최초 호출, 2 이상: 재시도)';

COMMENT ON COLUMN sched_external_api_call_log.http_status
IS 'HTTP 응답 상태 코드';

COMMENT ON COLUMN sched_external_api_call_log.started_at
IS 'API 호출 시작 일시';

COMMENT ON COLUMN sched_external_api_call_log.finished_at
IS 'API 호출 종료 일시';

COMMENT ON COLUMN sched_external_api_call_log.run_millis
IS 'API 호출 소요 시간(ms)';

COMMENT ON COLUMN sched_external_api_call_log.status
IS 'API 호출 상태';

COMMENT ON COLUMN sched_external_api_call_log.error_message
IS 'API 호출 실패 시 오류 메시지';

COMMENT ON COLUMN sched_external_api_call_log.created_at
IS '로그 생성 일시';


-- =========================================================
-- 5. Application user
-- =========================================================

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 6. Application role
-- =========================================================

CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 7. User - Role
-- =========================================================

CREATE TABLE app_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_app_user_role
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_aur_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id),

    CONSTRAINT fk_aur_role
        FOREIGN KEY (role_id)
        REFERENCES app_role (id)
);
