-- =========================================================
-- Scheduler application tables
-- PostgreSQL
-- =========================================================


-- =========================================================
-- 1. Job execution log
-- =========================================================

CREATE TABLE sched_exec_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fire_instance_id VARCHAR(120) NOT NULL,
    job_name VARCHAR(190) NOT NULL,
    job_group VARCHAR(190) NOT NULL,
    trigger_name VARCHAR(190),
    trigger_group VARCHAR(190),
    scheduled_fire_time TIMESTAMP(6),
    actual_fire_time TIMESTAMP(6),
    finished_at TIMESTAMP(6),
    run_millis BIGINT,
    status VARCHAR(20) NOT NULL,
    exception_message VARCHAR(2000),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. External API
-- =========================================================

CREATE TABLE sched_external_api (
    external_api_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_name VARCHAR(100) NOT NULL,
    api_url VARCHAR(1000) NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    enabled CHAR(1) NOT NULL DEFAULT 'Y',
    description VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_sched_external_api_enabled
        CHECK (enabled IN ('Y', 'N')),

    CONSTRAINT ck_sched_external_api_method
        CHECK (http_method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE'))
);


-- =========================================================
-- 3. External API parameter
-- =========================================================

CREATE TABLE sched_external_api_param (
    param_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_api_id BIGINT NOT NULL,
    param_location VARCHAR(20) NOT NULL,
    param_name VARCHAR(100) NOT NULL,
    value_type VARCHAR(30) NOT NULL,
    param_value VARCHAR(2000),
    value_format VARCHAR(100),
    required_yn CHAR(1) NOT NULL DEFAULT 'N',
    sort_order INTEGER NOT NULL DEFAULT 0,
    description VARCHAR(500),

    CONSTRAINT fk_external_api_param_api
        FOREIGN KEY (external_api_id)
        REFERENCES sched_external_api (external_api_id),

    CONSTRAINT ck_external_api_param_location
        CHECK (param_location IN ('HEADER', 'QUERY', 'BODY')),

    CONSTRAINT ck_external_api_param_required
        CHECK (required_yn IN ('Y', 'N')),

    CONSTRAINT ck_external_api_param_value_type
        CHECK (
            value_type IN (
                'STATIC',
                'CURRENT_DATE',
                'CURRENT_TIME',
                'CURRENT_DATETIME'
            )
        )
);


-- =========================================================
-- 4. External API call log
-- =========================================================

CREATE TABLE sched_external_api_call_log (
    api_call_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_api_id BIGINT NOT NULL,
    fire_instance_id VARCHAR(200),
    http_status INTEGER,
    started_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP(6),
    run_millis BIGINT,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(2000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 5. Application user
-- =========================================================

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 6. Application role
-- =========================================================

CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 7. User - Role
-- =========================================================

CREATE TABLE app_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_app_user_role
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_aur_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id),

    CONSTRAINT fk_aur_role
        FOREIGN KEY (role_id)
        REFERENCES app_role (id)
);


-- =========================================================
-- 8. External API retry policy
-- =========================================================

-- External API 호출 실패 시 사용할 재시도 정책 컬럼을 추가한다.
ALTER TABLE sched_external_api
    ADD COLUMN retry_enabled CHAR(1) NOT NULL DEFAULT 'N',
    ADD COLUMN max_retry_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN retry_interval_sec INTEGER NOT NULL DEFAULT 0;

COMMENT ON COLUMN sched_external_api.retry_enabled
IS 'External API 호출 실패 시 재시도 사용 여부 (Y/N)';

COMMENT ON COLUMN sched_external_api.max_retry_count
IS '최초 호출 실패 후 추가 재시도 최대 횟수';

COMMENT ON COLUMN sched_external_api.retry_interval_sec
IS 'External API 재시도 간격(초)';


-- =========================================================
-- 9. External API call retry history
-- =========================================================

-- External API 재시도 발생 시 각 호출 시도를 구분하기 위한 시도 번호 컬럼을 추가한다.
ALTER TABLE sched_external_api_call_log
    ADD COLUMN attempt_no INTEGER NOT NULL DEFAULT 1;

COMMENT ON COLUMN sched_external_api_call_log.attempt_no
IS 'External API 호출 시도 번호 (1: 최초 호출, 2 이상: 재시도)';

-- External API 1회 실행 단위를 식별하기 위한 실행 식별자 컬럼을 추가한다.
ALTER TABLE sched_external_api_call_log
    ADD COLUMN execution_id VARCHAR(36);

COMMENT ON COLUMN sched_external_api_call_log.execution_id
IS 'External API 1회 실행 단위를 식별하는 ID';