-- =========================================================
-- Application security tables
-- PostgreSQL
-- =========================================================


-- =========================================================
-- 1. Application user
-- =========================================================

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);


-- =========================================================
-- 2. Application role
-- =========================================================

CREATE TABLE app_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


-- =========================================================
-- 3. User - Role
-- =========================================================

CREATE TABLE app_user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT pk_app_user_role
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT fk_aur_user
        FOREIGN KEY (user_id)
        REFERENCES app_user (id),

    CONSTRAINT fk_aur_role
        FOREIGN KEY (role_id)
        REFERENCES app_role (id)
);