# Production DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Production logging
logging.level.org.mybatis=INFO
logging.level.org.mybatis.spring=INFO
logging.level.com.kji.scheduler.mapper=INFO