# Production DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Nginx 리버스 프록시 환경에서 원본 요청의 Host, Protocol 정보를 인식한다.
server.forward-headers-strategy=framework

# Production logging
logging.level.org.mybatis=INFO
logging.level.org.mybatis.spring=INFO
logging.level.com.kji.scheduler.mapper=INFO