spring.application.name=scheduler-service

# Quartz를 DB로 운영
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never

# Scheduler 이름
spring.quartz.scheduler-name=MyQuartzScheduler

# 예정된 실행 시각보다 60초 이상 지연된 Trigger를 misfire 대상으로 판단한다.
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000

# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.kji.scheduler.dto
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

logging.level.org.mybatis=DEBUG
logging.level.org.mybatis.spring=DEBUG
logging.level.com.msa=DEBUG
logging.level.com.kji.scheduler.mapper=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [fireId=%X{fireId}] %msg%n

# 세션 만료 시간
server.servlet.session.timeout=30m

# External API 호출 Timeout
external-api.connect-timeout=3000
external-api.read-timeout=10000