# Local DB
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler

# Local DB credentials
spring.config.import=optional:file:./config/application-postgresql-secret.properties

# Local logging
logging.level.org.mybatis=DEBUG
logging.level.org.mybatis.spring=DEBUG
logging.level.com.kji.scheduler.mapper=DEBUG

# Local Vue 개발 서버의 CORS 요청을 허용한다.
app.security.cors-allowed-origins=http://localhost:5173