# Local DB
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler

# Local DB credentials
spring.config.import=optional:file:./config/application-postgresql-secret.properties

# Local logging
logging.level.org.mybatis=DEBUG
logging.level.org.mybatis.spring=DEBUG
logging.level.com.msa=DEBUG
logging.level.com.kji.scheduler.mapper=DEBUG